openapi: 3.0.3
info:
  title: Fruityvice - OpenAPI 3.0
  description: |-
    A powerful webservice which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The webservice is completely free to use and contribute to.
  version: 1.0.1
externalDocs:
  description: Find out more about Fruityvice
  url: https://fruityvice.com/doc/index.html
servers:
  - url: https://fruityvice.com/api
tags:
  - name: fruit
    description: Everything about fruits
    externalDocs:
      description: Find out more
      url: https://fruityvice.com/doc/index.html
paths:
  /fruit/all:
    get:
      tags:
        - fruit
      summary: Gets list of all fruits in the database
      description: Gets list of all fruits in the database
      operationId: getAll
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'          
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  /fruit/{nutrition}:
    get:
      tags:
        - fruit
      summary: Searches database for fruits satisfying given conditions
      description: Get Fruits with given nutrition between min and max parameter. At least one query parameter has to be given.
      operationId: findFruitsByNutrition
      parameters:
        - name: nutrition
          in: path
          description: a nutrition to filter fruits by
          required: true
          schema:
            type: string
            enum:
              - carbohydrates
              - protein
              - fat
              - calories
              - sugar
        - name: min
          in: query
          description: minimum value for given nutrition
          required: false
          schema:
            type: number
        - name: max
          in: query
          description: maximum value for given nutrition
          required: false
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
        '400':
          description: Missing required parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You need to provide further parameter for the request to work!
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The fruit was not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  /fruit/family/{family}:
    get:
      tags:
        - fruit
      summary: Get all Fruits available in the database which belong to a given family
      description: Gets a list of fruits
      operationId: getFamily
      parameters:
        - name: family
          in: path
          description: Family to get all fruits in.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The fruit was not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  /fruit/genus/{genus}:
    get:
      tags:
        - fruit
      summary: Get all fruits available in the database which belong to a given genus
      description: Gets a list of fruits
      operationId: getGenus
      parameters:
        - name: genus
          in: path
          description: Genus to get all fruits in.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The fruit was not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  /fruit/order/{order}:
    get:
      tags:
        - fruit
      summary: Get all fruits available in the database which belong to a given order
      description: Gets a list of fruits
      operationId: getOrder
      parameters:
        - name: order
          in: path
          description: Order to get all fruits in.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The fruit was not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
components:
  schemas:
    Nutritions:
      type: object
      properties:
        carbohydrates:
          type: number
          description: Carbohydrates of the Fruit (per 100g) in gramm.
          example: 22
        protein:
          type: number
          description: Protein of the Fruit (per 100g) in gramm.
          example: 0
        fat:
          type: number
          description: Fat of the Fruit (per 100g) in gramm.
          example: 0.2
        calories:
          type: number
          description: Calories of the Fruit (per 100g) in gramm.
          example: 96
        sugar:
          type: number
          description: Sugar of the Fruit (per 100g) in gramm.
          example: 17.2
    Fruit:
      type: object
      properties:
        name:
          type: string
          description: Name of the Fruit.
          example: Banana
        id:
          type: integer
          description: ID of the Fruit.
          example: 2
        family:
          type: string
          description: Family of the Fruit.
          example: Musaceae
        genus:
          type: string
          description: Genus of the Fruit.
          example: Musa
        order:
          type: string
          description: Order of the Fruit.
          example: Zingiberales
        nutritions:
            $ref: '#/components/schemas/Nutritions'
